### ISSUE TITLE
【トップページ】投稿（ブログ）とお知らせのタイトル（h2）に投稿リストへのリンクを追加する

### ISSUE THREAD

**Issue by ghost** [vektor-inc/biz-vektor#155]

**Comment by dswebstudio** [comment]
hoverは色がつくほうだと各スキンとデザインのCSSを変える必要があるので、単にアンダーバーにしました。

**Comment by kurudrive** [comment]
クリック出来なかったりリンクがつかなかったり文字色が未調整なので一旦下記ブランチに移行
https://github.com/kurudrive/biz-vektor/tree/top_h2
