### ISSUE TITLE
【3PRエリア】スマホ用の画像がない場合ちょっと格好悪い（キャプチャー付き）

### ISSUE THREAD

**Issue by ghost** [vektor-inc/biz-vektor#156]
![no-small-images](https://cloud.githubusercontent.com/assets/9030574/5310444/97a110ba-7c76-11e4-9220-7f2ab57bb344.jpg)

上のようになっちゃいます。

**Comment by kurudrive** [comment]
構造上の問題があるのでちょっと保留
