### ISSUE TITLE
アップデート後のデザイン崩れについて

### ISSUE THREAD

**Issue by kenkonkan99** [vektor-inc/biz-vektor#270]
いつもお世話になっております。
私はノーマルのBizVektorを使用させて頂いており、ヘッダーメニューを7に設定しております。
アップデート後に、なぜかある一定のウィンドウの大きさを超えると、7つめのヘッダーが中途半端な2段目の位置に設置されます。
ウィンドウの幅を小さく→MENUの中に収納
ウィンドウを広く→7つめのヘッダーが2段目の左端に（これはわかる）
ウィンドウをさらに広く→7つが並列に並ぶ
ウィンドウをさらに広く→今まで1行だった（私のサイトで）4番目のヘッダータイトルが2行になり、それに引っかかるかのように、5番目のヘッダーの下になぜか7番目のヘッダーが移動
Calmly Braceを使用していたのですが、他のスキンにしてもやはり同じ現象が起こります。
もちろんながらこれまでウィンドウの幅が広がれば1行になるだけで、そのあと2行になるなんて言うことはありませんでした。
どのようにすれば修正できるのか、ご教示お願いします。

**Comment by kurudrive** [comment]
ちょっと私の環境では再現しなかったのですが、該当のURLを貼っていただく事はできますか？

**Comment by kenkonkan99** [comment]
ありがとうございます。
宜しくお願いします。

http://www.gotosagae.com/

**Comment by kurudrive** [comment]
ぱっと見特に問題がないように見受けられましたが、ブラウザは何をご利用でしょうか？

**Comment by kenkonkan99** [comment]
お世話になっております。
すみません、サファリで見たら、全く問題ございませんでした。
Firefoxで見ると、崩れます。

**Comment by kurudrive** [comment]
うーん・・・僕のFirefox 49.0.2 だと症状出ないですね〜・・・
問題の症状は全てのページで出るのでしょうか？
特定のページでだけ出ますか？

**Comment by kurudrive** [comment]
close : 1.9.11 でメニュー分割の仕様が変更された為
