### ISSUE TITLE
2カラム時の3PRの幅改善要望

### ISSUE THREAD

**Issue by honda3** [vektor-inc/biz-vektor#275]
トップページを２カラムにした場合、３PR幅が狭くなってしまうので是非ともヘッダー画像下にウィジェットエリア追加で３PRを追加できるようにしていただけないでしょうか。
お忙しいところ恐縮ですがご検討ください_(._.)_

**Comment by kurudrive** [comment]
@honda3 

実装いたしました。
配信まで今しばらくお待ちください！

**Comment by honda3** [comment]
お忙しい中ありがとうございます。
恐ろしく速いご対応感動で身体が震えております(;''∀'')
