### ISSUE TITLE
Grid Unitの表示について

### ISSUE THREAD

**Issue by Tommy1201** [vektor-inc/biz-vektor#282]
TOPページ・投稿一覧のGrid Unitが急に縦一列に表示されるようになり、横に並びません
どんな原因が考えられるでしょうか？テーマはGracefulを使っています

**Comment by kurudrive** [comment]
javascriptがエラーになってしまっているのだと思います。
最近有効化したプラグインなど停止してみてください。

**Comment by Tommy1201** [comment]
ありがとうございます。
解決しました！！！助かりました(*- -)(*_ _)ペコリ

**Comment by kurudrive** [comment]
無事解決したとの事で何よりです。
