### ISSUE TITLE
Wordpress 4.9.1 以降でのfront-page.phpの表示

### ISSUE THREAD

**Issue by gizmos0816** [vektor-inc/biz-vektor#292]
Wordpress 4.9.1以降にバージョンアップした際、
front-page.php、固定フロントページが表示されなくなりました。

ご確認、改善お願いいたします。

**Comment by kurudrive** [comment]
ご利用のBizVektorのバージョン
サーバーのPHPのバージョンを記載は何でしょうか？

**Comment by gizmos0816** [comment]
BizVektorバージョン: 1.10.1
サーバー PHPバージョン 5.6.30
上記動作環境で発生しています

**Comment by kurudrive** [comment]
弊社環境では発生しませんでしたので、
以下ご確認ください。

* プラグインを全て停止しても同様の症状かどうか？
* 他のテーマに切り替えても同様の症状かどうか？

それでも改善しない場合は
WordPressをインストールしたディレクトリにある wp-config.php の最後あたりに `define('WP_DEBUG', true); ` 記載してみて、エラーメッセージが表示されていましたらその内容をこちらに記載してください。

**Comment by gizmos0816** [comment]
失礼しました
コンテンツエリア（トップページ）にウィジェットが入っていたため、
表示されていなかったようです。

そちらを削除したら、表示されました。
ありがとうございます。
