### ISSUE TITLE
修正して使っています

### ISSUE THREAD

**Issue by pooh-kamakura** [vektor-inc/biz-vektor#329]
先日はPHP 8対応版ありがとうございます。

いくつか気になって修正して使っている部分がありますのでお伝えします。
もしも今後バージョンアップされることがあれば対応していただけると助かります。

/biz-vektor/plugins/disable-guide.php
33行目 リンク切れのためコメントアウト
		array('feed_url' => 'http://forum.bizvektor.com/feed/?post_type=topic', 'feed_title' => __( 'BizVektor Forum', 'biz-vektor' ), ), 
66行目　get_local_date()をget_date()に書き換える
					$test_date 	= $item->get_local_date();

/biz-vektor/inc/theme-options.php
791行目　$colors→$corlorsに書き換える
	foreach ($colors as $k => $v) {

**Comment by kurudrive** [comment]
@pooh-kamakura ありがとうございます。修正しました。
